services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: torrent_parser_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models:ro
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    # For low-power CPUs, set thread counts explicitly
    environment:
      - OMP_NUM_THREADS=2 # Adjust based on your CPU core count (e.g., N5105 has 4 cores)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
