name: Docker Build and Publish to GHCR

# Controls when the action will run.
# - Triggers on pushes to the 'main' branch.
# - Allows manual triggering from the Actions tab on GitHub.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Environment variables available to all jobs in the workflow
env:
  # The GitHub Container Registry to push to
  REGISTRY: ghcr.io
  # The name of the Docker image, using the repository name
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    # Set permissions for the GITHUB_TOKEN for authentication with the container registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Create a 'latest' tag for the default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Create a tag based on the Git SHA
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable build cache for faster subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
